package pojo;
// Generated Nov 19, 2017 9:28:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Consultatii generated by hbm2java
 */
public class Consultatii  implements java.io.Serializable {


     private int idConsultatie;
     private Medici medici;
     private Pacienti pacienti;
     private Date data;
     private String diagnostic;
     private String tratament;

    public Consultatii() {
    }

	
    public Consultatii(Medici medici, Pacienti pacienti, Date data) {
        
        this.medici = medici;
        this.pacienti = pacienti;
        this.data = data;
    }
    public Consultatii(Medici medici, Pacienti pacienti, Date data, String diagnostic, String tratament) {
       
       this.medici = medici;
       this.pacienti = pacienti;
       this.data = data;
       this.diagnostic = diagnostic;
       this.tratament = tratament;
    }
   
    public int getIdConsultatie() {
        return this.idConsultatie;
    }
    
    public void setIdConsultatie(int idConsultatie) {
        this.idConsultatie = idConsultatie;
    }
    public Medici getMedici() {
        return this.medici;
    }
    
    public void setMedici(Medici medici) {
        this.medici = medici;
    }
    public Pacienti getPacienti() {
        return this.pacienti;
    }
    
    public void setPacienti(Pacienti pacienti) {
        this.pacienti = pacienti;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getDiagnostic() {
        return this.diagnostic;
    }
    
    public void setDiagnostic(String diagnostic) {
        this.diagnostic = diagnostic;
    }
    public String getTratament() {
        return this.tratament;
    }
    
    public void setTratament(String tratament) {
        this.tratament = tratament;
    }




}


