package pojo;
// Generated Nov 19, 2017 9:28:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Medici generated by hbm2java
 */
public class Medici  implements java.io.Serializable {


     private Integer idMedic;
     private String nume;
     private String prenume;
     private String sectie;
     private Set<Consultatii> consultatiis = new HashSet<Consultatii>(0);

    public Medici() {
    }

	
    public Medici(String nume, String prenume) {
        this.nume = nume;
        this.prenume = prenume;
    }
    public Medici(String nume, String prenume, String sectie) {
       this.nume = nume;
       this.prenume = prenume;
       this.sectie = sectie;
       
    }
   
    public Integer getIdMedic() {
        return this.idMedic;
    }
    
    public void setIdMedic(Integer idMedic) {
        this.idMedic = idMedic;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public String getPrenume() {
        return this.prenume;
    }
    
    public void setPrenume(String prenume) {
        this.prenume = prenume;
    }
    public String getSectie() {
        return this.sectie;
    }
    
    public void setSectie(String sectie) {
        this.sectie = sectie;
    }
    public Set<Consultatii> getConsultatiis() {
        return this.consultatiis;
    }
    
    public void setConsultatiis(Set<Consultatii> consultatiis) {
        this.consultatiis = consultatiis;
    }




}


