package pojo;
// Generated Nov 19, 2017 9:28:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pacienti generated by hbm2java
 */
public class Pacienti  implements java.io.Serializable {


     private Integer idPacient;
     private String nume;
     private String prenume;
     private String telefon;
     private String adresa;
     private Integer varsta;
     private Set<Consultatii> consultatiis = new HashSet<Consultatii>(0);

    public Pacienti() {
    }

	
    public Pacienti(String nume, String prenume) {
        this.nume = nume;
        this.prenume = prenume;
    }
    public Pacienti(String nume, String prenume, String telefon, String adresa, Integer varsta) {
       this.nume = nume;
       this.prenume = prenume;
       this.telefon = telefon;
       this.adresa = adresa;
       this.varsta = varsta;
       
    }
   
    public Integer getIdPacient() {
        return this.idPacient;
    }
    
    public void setIdPacient(Integer idPacient) {
        this.idPacient = idPacient;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public String getPrenume() {
        return this.prenume;
    }
    
    public void setPrenume(String prenume) {
        this.prenume = prenume;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }
    public Integer getVarsta() {
        return this.varsta;
    }
    
    public void setVarsta(Integer varsta) {
        this.varsta = varsta;
    }
    public Set<Consultatii> getConsultatiis() {
        return this.consultatiis;
    }
    
    public void setConsultatiis(Set<Consultatii> consultatiis) {
        this.consultatiis = consultatiis;
    }




}


